/*
 * Copyright 2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.springframework.boot.reflectionprocessor;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.util.Date;
import java.util.List;

import javax.annotation.processing.ProcessingEnvironment;
import javax.tools.FileObject;
import javax.tools.StandardLocation;

import org.springframework.boot.graal.reflectconfig.JsonMarshaller;
import org.springframework.boot.graal.reflectconfig.ReflectionDescriptor;

/**
 * A {@code ConfigFileStorageManager} is responsible for the reading/writing of native-image configuration information from/to
 * the filesystem. The data needs to be stored under the <tt>META-INF/native-image</tt> folder.
 *
 * @author Andy Clement
 */
public class ConfigFileStorageManager {

	// TODO doesn't include the groupid/artifactid in the path (native-image/group/artifact/...)
	private static final String REFLECT_CONFIG_PATH = "META-INF/native-image/reflection-config.json";

	private static final String RESOURCE_CONFIG_PATH = "META-INF/native-image/resource-config.json";
	
	private static final String NATIVE_IMAGE_PROPERTIES_FILE = "META-INF/native-image/native-image.properties";

	private final ProcessingEnvironment environment;

	public ConfigFileStorageManager(ProcessingEnvironment environment) {
		this.environment = environment;
	}

	public ReflectionDescriptor readReflectConfig() {
		try (InputStream in = getConfigResource(REFLECT_CONFIG_PATH).openInputStream()) {
			if (in != null) {
				return JsonMarshaller.readReflectConfig(in);
			}
		} catch (IOException ex) {
			// ok
		} catch (Exception ex) {
			throw new RuntimeException("Invalid config in '" + REFLECT_CONFIG_PATH + "': " + ex.getMessage());
		}
		return null;
	}

	public List<String> readResourceConfig() {
		try (InputStream in = getConfigResource(RESOURCE_CONFIG_PATH).openInputStream()) {
			if (in != null) {
				return JsonMarshaller.readResourceConfig(in);
			}
		} catch (IOException ex) {
			// ok
		} catch (Exception ex) {
			throw new RuntimeException("Invalid config in '" + RESOURCE_CONFIG_PATH + "': " + ex.getMessage());
		}
		return null;
	}

	public void writeResourceConfig(List<String> resourcePatterns) throws IOException {
		if (!resourcePatterns.isEmpty()) {
			try (OutputStream outputStream = createConfigResource(RESOURCE_CONFIG_PATH).openOutputStream()) {
				new JsonMarshaller().writeResourceConfig(resourcePatterns, outputStream);
			}
		}
	}

	public void writeReflectionConfig(ReflectionDescriptor metadata) throws IOException {
		if (!metadata.isEmpty()) {
			try (OutputStream outputStream = createConfigResource(REFLECT_CONFIG_PATH).openOutputStream()) {
				new JsonMarshaller().writeReflectConfig(metadata, outputStream);
			}
		}
	}

	private FileObject getConfigResource(String location) throws IOException {
		return this.environment.getFiler().getResource(StandardLocation.CLASS_OUTPUT, "",
				location);
	}

	private FileObject createConfigResource(String location) throws IOException {
		return this.environment.getFiler().createResource(StandardLocation.CLASS_OUTPUT,
				"", location);
	}

	public void writeIfNecessary(ReflectionDescriptor reflectionDescriptor, List<String> resourcePatterns)
			throws IOException {
		System.out.println("Outputting data: cds?"+!reflectionDescriptor.isEmpty()+"  rps?"+!resourcePatterns.isEmpty());
		if (!reflectionDescriptor.isEmpty()) {
			writeReflectionConfig(reflectionDescriptor);
		}
		// Write out the resources.json file
		if (!resourcePatterns.isEmpty()) {
			writeResourceConfig(resourcePatterns);
		}
		// Write out the native-image.properties
		// For example: Args=-H:ReflectionConfigurationResources=${.}/reflection-config.json
		try (OutputStream outputStream = createConfigResource(NATIVE_IMAGE_PROPERTIES_FILE).openOutputStream()) {
			PrintWriter pw = new PrintWriter(outputStream);
			pw.println("Generated by Spring Graal annotation processor at "+new Date().toString());
			StringBuilder argsValue = new StringBuilder();
			if (!reflectionDescriptor.isEmpty()) {
				argsValue.append(" -H:ReflectionConfigurationResources=${.}/reflection-config.json");
			}
			if (!resourcePatterns.isEmpty()) {
				argsValue.append(" -H:ResourceConfigurationFiles=${.}/resource-config.json");
			}
			pw.println("Args="+argsValue.toString().trim());
			pw.close();
		}
	}

}
